.TH "namecheap-ddns-todo" 1 "Sun Jun 18 2023" "Version 0.1.2" "namecheap-ddns" \" -*- nroff -*-
.ad l
.nh
.SH NAME
namecheap-ddns-todo \- namecheap-ddns TODO 
.PP

.IP "\(bu" 2
[ ] Add a message to every fatal exception to please file an issue report on GitHub\&.
.IP "\(bu" 2
[ ] URLs that can be used for testing purposes:
.IP "  \(bu" 4
[ ] https://httpstat.us/ - can return every HTTP error code, as well as randomize them\&.’’
.PP

.IP "\(bu" 2
[ ] Don’t log password in plaintext, especially to a log file\&. I don’t even want it in the terminal to be honest\&. 
.PP

