.TH "nc-ddns.py" 1 "Sun Jun 18 2023" "Version 0.1.2" "namecheap-ddns" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nc-ddns.py \- Namecheap Dyanmic DNS utilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "str \fBnc\-ddns\&.ansi_esc\fP (str codes)"
.br
.RI "Creates an ANSI escape sequence using the information supplied in\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.ansi_esc_end\fP ()"
.br
.RI "Ends an ANSI escape sequence and resets all styles and colors to normal\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.ansi_esc_basic\fP (str msg, int attr=0, int fg=39, int bg=49)"
.br
.RI "Generates a string wrapped in the begin/end sequences necessary to render 16-color styling in the terminal\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.error_msg\fP (str msg)"
.br
.RI "Generates a string that is red and bold in appearance for displaying errors\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.success_msg\fP (str msg)"
.br
.RI "Generates a string that is green and bold in appearance for displaying success messages\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.warning_msg\fP (str msg)"
.br
.RI "Generates a string that is yellow and bold in appearance for displaying warnings\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBnc\-ddns\&.HTTP_TIMEOUTS\fP = (6\&.05, 27\&.05)"
.br
.RI "The default timeouts for an HTTP GET request, in seconds (connect, read)\&. "
.ti -1c
.RI "int \fBnc\-ddns\&.MAX_RETRIES\fP = 15"
.br
.RI "The maximim number of times to retry a failed HTTP request\&. "
.ti -1c
.RI "int \fBnc\-ddns\&.MAX_REDIRECTS\fP = 3"
.br
.RI "The maximum HTTP redirects to tolerate\&. "
.ti -1c
.RI "float \fBnc\-ddns\&.BACKOFF_FACTOR\fP = 1\&.5"
.br
.RI "The factor used to determine the next exponential backoff interval\&. "
.ti -1c
.RI "float \fBnc\-ddns\&.BACKOFF_JITTER\fP = 0\&.325"
.br
.RI "The amount of jitter to apply to the backoff interval\&. "
.ti -1c
.RI "tuple \fBnc\-ddns\&.MAX_BACKOFF\fP = (5\&.0 * 60\&.0)"
.br
.RI "The longest possible retry backoff interval, in seconds\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.NC_DDNS_URL\fP = 'https://dynamicdns\&.park\-your\-domain\&.com/update'"
.br
.RI "Namecheap DDNS API endpoint\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.NC_DDNS_GH_REPO\fP = 'https://github\&.com/aremmell/namecheap\-ddns'"
.br
.RI "The GitHub repository that this script was born in\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.NC_DDNS_GH_README\fP = f'{\fBNC_DDNS_GH_REPO\fP}/blob/main/README\&.md'"
.br
.RI "The link directly to README\&.md\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.NC_DDNS_GH_NEWISSUE\fP = f'{\fBNC_DDNS_GH_REPO\fP}/issues/new/choose'"
.br
.RI "The link directly to opening a new issue\&. "
.ti -1c
.RI "str \fBnc\-ddns\&.IP_SERVICE\fP = 'https://api\&.ipify\&.org'"
.br
.RI "The default service for resolution of public IP addresses\&. "
.ti -1c
.RI "int \fBnc\-ddns\&.PRINT_XML_RESPONSE_BODY\fP = 0"
.br
.RI "Whether or not to print the response body from Namecheap's server in the debug log\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namecheap Dyanmic DNS utilities\&. 

Namecheap offers a great DDNS service, but the software (and router integration) available to let Namecheap's DNS servers know when your public IP address has changed are not plentiful or portable\&.
.PP
This script aims to become the defacto standard for manual and automated (e\&.g\&. via cron) updating of Namecheap DDNS records\&.
.PP
\fBAuthor\fP
.RS 4
Ryan M\&. Lederman lederman@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
The MIT License (MIT)
.RE
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.SH "Function Documentation"
.PP 
.SS " str nc\-ddns\&.ansi_esc (str codes)"

.PP
Creates an ANSI escape sequence using the information supplied in\&. 
.PP
\fBParameters\fP
.RS 4
\fIcodes\&.\fP 
.RE
.PP

.SS " str nc\-ddns\&.ansi_esc_basic (str msg, int  attr = \fC0\fP, int  fg = \fC39\fP, int  bg = \fC49\fP)"

.PP
Generates a string wrapped in the begin/end sequences necessary to render 16-color styling in the terminal\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP The string to colorize/style\&. 
.br
\fIattr\fP 0=normal, 1=bold, 2=dim text 
.br
\fIfg\fP Foreground text color\&. The default value is the terminal's default\&. 
.br
\fIbg\fP Background text color\&. The default value is the terminal's default\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "str nc\-ddns\&.IP_SERVICE = 'https://api\&.ipify\&.org'"

.PP
The default service for resolution of public IP addresses\&. 
.PP
\fBNote\fP
.RS 4
This isn't necessary to update your address with Namecheap; it is simply provided as a convenience\&. 
.RE
.PP

.SS "int nc\-ddns\&.PRINT_XML_RESPONSE_BODY = 0"

.PP
Whether or not to print the response body from Namecheap's server in the debug log\&. Disabled by default\&. Change this to 1 to enable\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for namecheap-ddns from the source code\&.
